### PR TITLE
Implement match controller

### PR DESCRIPTION
**Pull request by IgorLeonenko**
This change is [Reviewable](https://reviewable.io/reviews/igorleonenko/matches/2)

### CODE REVIEW

**Comment by jotka87** [comment]
Reviewed 28 of 36 files at r1.
Review status: 27 of 35 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/application_controller.rb, line 8 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRd17xRfHZaUyRWkRvu:-KRd17xRfHZaUyRWkRvv:b854x6o) ([raw file](https://github.com/igorleonenko/matches/blob/2a16b6c92c724f1eb3972d9f7d7a7613712d593e/app/controllers/application_controller.rb#L8)):_

> ``` Ruby
>   private
> 
>     def render_404
> ```

there is no need for another indentation, all methods (public and private) should be indented the same.

---

_[app/views/matches/_form.html.slim, line 2 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRd2sW0nDJWHba-cYyU:-KRd2sW0nDJWHba-cYyV:bu84itc) ([raw file](https://github.com/igorleonenko/matches/blob/2a16b6c92c724f1eb3972d9f7d7a7613712d593e/app/views/matches/_form.html.slim#L2)):_

> ``` Slim
> = simple_form_for(@match, html: { class: 'form-horizontal' }) do |f|
>     = f.input :name
> ```

additional level of indentation here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by jotka87** [comment]
Reviewed 7 of 36 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[Gemfile, line 50 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRdL83Lw6OJAVaVF6n4:-KRdL83Lw6OJAVaVF6n5:b-s4twgd) ([raw file](https://github.com/igorleonenko/matches/blob/2a16b6c92c724f1eb3972d9f7d7a7613712d593e/Gemfile#L50)):_

> ``` Ruby
>   # Call 'byebug' anywhere in the code to stop execution and get a debugger console
>   gem 'byebug', platform: :mri
>   gem 'rspec-rails', '~> 3.5'
> ```

why did you removed version? It's a good practise to specify version for each gem

---

_[app/controllers/matches_controller.rb, line 19 at r2](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRdMRuZoheGm1cu34SK:-KRdMRuZoheGm1cu34SL:bs0rzcc) ([raw file](https://github.com/igorleonenko/matches/blob/8f45a09b65dd33d3d5d814ce22f383b321c5ea9b/app/controllers/matches_controller.rb#L19)):_

> ``` Ruby
>     if @match.save
>       flash[:notice] = 'Match created sucessfully'
>       redirect_to match_path(@match)
> ```

could be simply `@match` instead of `match_path(@match)`

---

_[spec/controllers/matches_controller_spec.rb, line 5 at r2](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRdMxHmgauqNgWEXOxR:-KRdMxHmgauqNgWEXOxS:bn9i169) ([raw file](https://github.com/igorleonenko/matches/blob/8f45a09b65dd33d3d5d814ce22f383b321c5ea9b/spec/controllers/matches_controller_spec.rb#L5)):_

> ``` Ruby
> RSpec.describe MatchesController, type: :controller do
>   let(:test_match) { create(:match, home_team: create(:team_with_users), invited_team: create(:team_with_users)) }
>   # let(:new_match) { build(:match, home_team: test_match.home_team, invited_team: test_match.invited_team) }
> ```

please, either uncomment that or remove it

---

_[spec/views/games/index.html.slim_spec.rb, line 3 at r2](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRdMkk9dboL1L3GQXfS:-KRdMkk9dboL1L3GQXfT:b-qim1jk) ([raw file](https://github.com/igorleonenko/matches/blob/8f45a09b65dd33d3d5d814ce22f383b321c5ea9b/spec/views/games/index.html.slim_spec.rb#L3)):_

> ``` Ruby
> require 'rails_helper'
> 
> RSpec.describe "games/index.html.slim", type: :view do
> ```

you can remove all of the view specs

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by IgorLeonenko** [comment]
_[Gemfile, line 50 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRdL83Lw6OJAVaVF6n4:-KRgi_NEyNF1_69uZANg:bbu85w5) ([raw file](https://github.com/igorleonenko/matches/blob/2a16b6c92c724f1eb3972d9f7d7a7613712d593e/Gemfile#L50)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> why did you removed version? It's a good practise to specify version for each gem
> </details>
> sorry, just play with "assigns" method in rspec. in the end I was add gem "rails-controller-testing"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by jotka87** [comment]
Reviewed 6 of 11 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by jotka87** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[spec/controllers/matches_controller_spec.rb, line 43 at r4](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRhYcmgEkUBrIQwY6mB:-KRhYcmgEkUBrIQwY6mC:b-19da7g) ([raw file](https://github.com/igorleonenko/matches/blob/43509ae6282164bd704c6ab37b3ccf28741c74f7/spec/controllers/matches_controller_spec.rb#L43)):_

> ``` Ruby
> 
>       it 'create a new match' do
>         expect{ subject }.to change(Match, :count).by(1)
> ```

add space between expect and a block

---

_[spec/factories/matches.rb, line 4 at r4](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRha8NhE-wf5OGQQ8Yj:-KRha8Ni2xjxQC-HGA7x:bqebhii) ([raw file](https://github.com/igorleonenko/matches/blob/43509ae6282164bd704c6ab37b3ccf28741c74f7/spec/factories/matches.rb#L4)):_

> ``` Ruby
>   factory :match do
>     name   { Faker::Lorem.characters(10) }
>     game_id   { create(:game).id }
> ```

why this change?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by jotka87** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by IgorLeonenko** [comment]
_[spec/factories/matches.rb, line 4 at r4](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRha8NhE-wf5OGQQ8Yj:-KRhhBmOv7nUfjg_bNx0:bbrvhcw) ([raw file](https://github.com/igorleonenko/matches/blob/43509ae6282164bd704c6ab37b3ccf28741c74f7/spec/factories/matches.rb#L4)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> why this change?
> </details>
> because in controller require parametr is 'game_id'.  When I pass Game like object, the create test return false by unpermitted param 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by jotka87** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/factories/matches.rb, line 4 at r4](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRha8NhE-wf5OGQQ8Yj:-KRhrXyHo4QCdUe-5N-o:b-xjw7z0) ([raw file](https://github.com/igorleonenko/matches/blob/43509ae6282164bd704c6ab37b3ccf28741c74f7/spec/factories/matches.rb#L4)):_
<details><summary>

<i>Previously, IgorLeonenko (Igor) wrote…</i></summary>



> because in controller require parametr is 'game_id'.  When I pass Game like object, the create test return false by unpermitted param 
> </details>
> hm, maybe try adding `game_id { game.id }` in the factory?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by jotka87** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/factories/matches.rb, line 4 at r4](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRha8NhE-wf5OGQQ8Yj:-KRhrkzu8ceIVYkHqAYA:bv61te4) ([raw file](https://github.com/igorleonenko/matches/blob/43509ae6282164bd704c6ab37b3ccf28741c74f7/spec/factories/matches.rb#L4)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> hm, maybe try adding `game_id { game.id }` in the factory?
> </details>
> and leave the old `game { create(:game) }`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by IgorLeonenko** [comment]
_[spec/factories/matches.rb, line 4 at r4](https://reviewable.io:443/reviews/igorleonenko/matches/2#-KRha8NhE-wf5OGQQ8Yj:-KRhy3Ob1ZBDDQMTPsHW:b-ukpvpr) ([raw file](https://github.com/igorleonenko/matches/blob/43509ae6282164bd704c6ab37b3ccf28741c74f7/spec/factories/matches.rb#L4)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> and leave the old `game { create(:game) }`
> </details>
> in this way it's also work :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Comment by jotka87** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/2)_

**Pull request merged**
