### PR TITLE
Implement tournament

### PR DESCRIPTION
**Pull request by IgorLeonenko**
This change is [Reviewable](https://reviewable.io/reviews/igorleonenko/matches/4)

### CODE REVIEW

**Comment by wmaciejak** [comment]
I think, you can delete empty files like `sessions.coffee`, or `users.coffee` :)

---

Reviewed 38 of 45 files at r1.
Review status: 38 of 45 files reviewed at latest revision, 5 unresolved discussions.

---

_[app/controllers/application_controller.rb, line 16 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/4#-KS3Cp69fkU1fMlztwJd:-KS3Cp69fkU1fMlztwJe:bvs0me1) ([raw file](https://github.com/igorleonenko/matches/blob/fef4384dfa2119f977781b957b1de92c08ad7b26/app/controllers/application_controller.rb#L16)):_

> ``` Ruby
> 
>   def current_user
>     @current_user ||= User.find(session[:user_id]) if session[:user_id]
> ```

What will happen if session will be `nil` ?

---

_[app/uploaders/tournament_picture_uploader.rb, line 15 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/4#-KS6s50fpqrwzgxuHaMe:-KS6s50fpqrwzgxuHaMf:b-x460yf) ([raw file](https://github.com/igorleonenko/matches/blob/fef4384dfa2119f977781b957b1de92c08ad7b26/app/uploaders/tournament_picture_uploader.rb#L15)):_

> ``` Ruby
> 
>   def remember_cache_id(new_file)
>     @cache_id_was = cache_id
> ```

What it is `cache_id`? Where it is define?

---

_[config/routes.rb, line 6 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/4#-KS6sbzhrMLCBSP4GGni:-KS6sbzhrMLCBSP4GGnj:bm7c1q0) ([raw file](https://github.com/igorleonenko/matches/blob/fef4384dfa2119f977781b957b1de92c08ad7b26/config/routes.rb#L6)):_

> ``` Ruby
>   resources :matches
> 
>   resources :users, only: [:create]
> ```

If you have only one action in `except:` or `only:`, I think you can put it without brackets :) 

---

_[db/migrate/20160916150107_create_tournaments.rb, line 6 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/4#-KS6t6nlUmb2sJFvIUc3:-KS6t6nlUmb2sJFvIUc4:b-9kfnaw) ([raw file](https://github.com/igorleonenko/matches/blob/fef4384dfa2119f977781b957b1de92c08ad7b26/db/migrate/20160916150107_create_tournaments.rb#L6)):_

> ``` Ruby
>       t.string :title, null: false
>       t.text :description
>       t.datetime :start_date, null: false, default: Time.now.to_date
> ```

`Time.zone.now.to_date`, please read about problems with `Time.now` [Article](http://danilenko.org/2012/7/6/rails_timezones/) :)
And please use rubocop gem :)

---

_[spec/factories/users.rb, line 10 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/4#-KS6yqZRmKr2Lnp6y3Hw:-KS6yqZRmKr2Lnp6y3Hx:bw1fqoa) ([raw file](https://github.com/igorleonenko/matches/blob/fef4384dfa2119f977781b957b1de92c08ad7b26/spec/factories/users.rb#L10)):_

> ``` Ruby
>   end
> 
>   factory :user_admin do
> ```

You can use :trait insted of creating new factory :)
[Article](https://robots.thoughtbot.com/remove-duplication-with-factorygirls-traits)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/4#-:-KS6q2MnmWH7hR9KzEx-:buohmy0)_

**Comment by wmaciejak** [comment]
Reviewed 1 of 45 files at r1.
Review status: 39 of 45 files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/4)_

**Comment by IgorLeonenko** [comment]
_[app/uploaders/tournament_picture_uploader.rb, line 15 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/4#-KS6s50fpqrwzgxuHaMe:-KSBLYE7RBX15x1UDBDU:b-hvkyp2) ([raw file](https://github.com/igorleonenko/matches/blob/fef4384dfa2119f977781b957b1de92c08ad7b26/app/uploaders/tournament_picture_uploader.rb#L15)):_
<details><summary>

<i>Previously, wojtekmaciej (Wojciech Maciejak) wrote…</i></summary>



> What it is `cache_id`? Where it is define?
> </details>
> it's come from this tutorial for carrierwave: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Delete-cache-garbage-directories

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/4)_

**Comment by IgorLeonenko** [comment]
_[app/controllers/application_controller.rb, line 16 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/4#-KS3Cp69fkU1fMlztwJd:-KSCE289wny4KEr3UN1B:b-xptley) ([raw file](https://github.com/igorleonenko/matches/blob/fef4384dfa2119f977781b957b1de92c08ad7b26/app/controllers/application_controller.rb#L16)):_

> session
> user will be logged out :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/4)_

**Comment by wmaciejak** [comment]
_[app/uploaders/tournament_picture_uploader.rb, line 15 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/4#-KS6s50fpqrwzgxuHaMe:-KSDBer4ysUnEwnZRgj1:b4c9lyr) ([raw file](https://github.com/igorleonenko/matches/blob/fef4384dfa2119f977781b957b1de92c08ad7b26/app/uploaders/tournament_picture_uploader.rb#L15)):_
<details><summary>

<i>Previously, IgorLeonenko (Igor) wrote…</i></summary>



> it's come from this tutorial for carrierwave: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Delete-cache-garbage-directories
> </details>
> :thumbsup: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/4)_

**Comment by wmaciejak** [comment]
_[app/controllers/application_controller.rb, line 16 at r1](https://reviewable.io:443/reviews/igorleonenko/matches/4#-KS3Cp69fkU1fMlztwJd:-KSDB-i5v1oRM0a3fejw:bltjro6) ([raw file](https://github.com/igorleonenko/matches/blob/fef4384dfa2119f977781b957b1de92c08ad7b26/app/controllers/application_controller.rb#L16)):_
<details><summary>

<i>Previously, IgorLeonenko (Igor) wrote…</i></summary>



> > session
> > user will be logged out :)
> > </details>
> > Yup, I know, but what will happen if in this place session will be nil? I think controller will raise error:
> > `NoMethodError: undefined method `[]' for nil:NilClass`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/4)_

**Comment by wmaciejak** [comment]
Reviewed 1 of 45 files at r1, 37 of 40 files at r2.
Review status: 49 of 53 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/4)_

**Comment by wmaciejak** [comment]
Reviewed 3 of 40 files at r2.
Review status: 52 of 53 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/igorleonenko/matches/4)_

**Pull request merged**
